# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20170917_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ip',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='user_agent',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
