# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20170918_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(default='NULL', max_length=200)),
                ('ip', models.CharField(default='NULL', max_length=200)),
            ],
        ),
    ]
