# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20170918_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ip',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
